# Generated by Django 6.1 on 2026-08-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='John Doe', max_length=255)),
                ('role', models.CharField(default='Administrator', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
        ),
    ]
