# Generated by Django 6.1 on 2026-08-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ano_format',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sno_format',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
