# Generated by Django 6.0.3 on 2026-08-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_userprofile_ano_format_userprofile_sno_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
