# Generated by Django 6.1 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_customer_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_id_no_format',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
